# analysis_options.yaml
# Minimal Dart/Flutter analyzer configuration

# Use recommended Flutter lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Important lints
    avoid_print: false            # allow print for debugging
    always_specify_types: true    # require type annotations
    avoid_empty_else: true        # prevent empty else blocks
    unnecessary_null_checks: true # avoid redundant null checks
    prefer_single_quotes: true    # enforce single quotes for strings

analyzer:
  exclude:
    - "**/*.g.dart"                     # Exclude generated files
    - "**/*.freezed.dart"               # Exclude Freezed-generated files
    - "**/generated_plugin_registrant.dart"
  errors:
    # Treat critical issues as errors
    unused_local_variable: error
    invalid_annotation_target: error
    always_specify_types: ignore
