name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # or your version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get
        working-directory: base_demo

      # Run Flutter Analyzer
      - name: Analyze project
        run: flutter analyze
        working-directory: base_demo

      # Run tests
      - name: Run tests
        run: flutter test
        working-directory: base_demo

      # Build Android APK
      - name: Build APK
        run: flutter build apk --release
        working-directory: base_demo

      # Upload build artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: base_demo/build/app/outputs/flutter-apk/app-release.apk
